

export default [
        {
        label:'招聘信息管理',
        to:'',
        children:[
                        {
                label:'添加招聘信息',
                to:'/admin/zhaopinxinxiadd',
            },
                        {
                label:'招聘信息列表',
                to:'/admin/zhaopinxinxi_faburen',
            },
                        {
                label:'测试试卷列表',
                to:'/admin/ceshishijuan_faburen',
            },
                        {
                label:'测试试题列表',
                to:'/admin/ceshishiti_faburen',
            },
                        {
                label:'测试结果列表',
                to:'/admin/ceshijieguo_faburen',
            },
                        {
                label:'测试成绩查询',
                to:'/admin/ceshichengji_faburen',
            },
                    ]
    },
        {
        label:'求职申请管理',
        to:'',
        children:[
                        {
                label:'求职申请列表',
                to:'/admin/qiuzhishenqing_faburen',
            },
                        {
                label:'求职申请审核',
                to:'/admin/shenqingshenhe_faburen',
            },
                        {
                label:'面试通知',
                to:'/admin/mianshitongzhi_faburen',
            },
                        {
                label:'面试结果',
                to:'/admin/mianshijieguo_faburen',
            },
                    ]
    },
        {
        label:'交流管理',
        to:'',
        children:[
                        {
                label:'交流查询',
                to:'/admin/jiaoliu_shouxinren',
            },
                    ]
    },
        {
        label:'个人中心',
        to:'',
        children:[
                        {
                label:'修改个人资料',
                to:'/admin/yongrendanweiupdtself',
            },
                        {
                label:'修改密码',
                to:'/admin/mod',
            },
                    ]
    },
    ]
